## Checking the configurations of the numpy library

In [15]:
import numpy as np
# if configured thru' Anaconda by default the highly optimized versions of the libraries such as
#  ATLAS, OpenBLAS, Intel MKL are installed. Care needs to be taken if stand alone version is installed
#  please check if the below libraries are present with correct version. Dealing with matrices, using specialized 
#  code from these libraries gives you 10x speed!!
np.__config__.show()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/softwares/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'D:/softwares/Anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/softwares/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'D:/softwares/

## Creating numpy arrays

In [29]:
# Creating 1D and 2D Numpy Arrays
b = np.array([1,2,3])           # 1D array
c = np.array([[1,2],[3,4]])     # 2D array

ones = np.ones(4)         # 1D array of ones
zeros = np.zeros(4)       # 1D array of zeros
d = np.random.randn(4)    # 1D array of random normal entries

A = np.ones((4,3))          # 2D array of ones
B = np.zeros((4,3))         # 2D array of zeros
C = np.random.randn(4,3)  # 2D array of radnom normal entries

I = np.eye(5)             # Identity matrix
D = np.diag(np.random.randn(3))

In [30]:
print("####### 1D array #########")
print("b = \n", b)
print("c = \n", c)
print("ones = \n", ones)
print("zeros = \n", zeros)
print("d = \n", d)
print("####### 2D array #########")
print("A = \n", A)
print("B = \n", B)
print("C = \n", C)
print("####### Identity Matrix #########")
print("I = \n", I)
print("####### Diagonal Matrix #########")
print("D = \n", D)


####### 1D array #########
b = 
 [1 2 3]
c = 
 [[1 2]
 [3 4]]
ones = 
 [1. 1. 1. 1.]
zeros = 
 [0. 0. 0. 0.]
d = 
 [ 0.39701596  1.201174    0.35331575 -1.37595174]
####### 2D array #########
A = 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
C = 
 [[-0.21859226  0.50128097 -0.18288921]
 [ 0.37194507 -0.02513789 -0.4227334 ]
 [ 0.86072348  0.70948967  0.01200847]
 [ 0.07280889 -0.95992071 -0.09532582]]
####### Identity Matrix #########
I = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
####### Diagonal Matrix #########
D = 
 [[ 1.48838321  0.          0.        ]
 [ 0.         -1.26650211  0.        ]
 [ 0.          0.         -1.21079961]]


In [31]:
type(b)

numpy.ndarray

## Indexing into Numpy Array

In [69]:
A = np.arange(20).reshape((5,4))
print("A = \n", A)
print(A[0,0])    # select single entry
print(A[0,:])    # select single row
print(A[0:3,1])

# integer indexing
print()
idx_int = np.array([0,1,2])
print(A[idx_int, 2])

# boolean indexing
print()
idx_bool = np.array([True, True, True, False, False])
print(A[idx_bool, 2])

# fancy indexing on 2D
print()
idx_bool2 = np.array([True, False, True, False])
print(A[idx_bool,:][:, idx_bool2])

A = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
0
[0 1 2 3]
[1 5 9]

[ 2  6 10]

[ 2  6 10]

[[ 0  2]
 [ 4  6]
 [ 8 10]]


## Basic operations on Arrays

In [74]:
A = np.random.randn(5,4)
A = np.arange(20).reshape((5,4))
B = np.random.randn(5,4)
x = np.random.randn(4)
x = np.array([1,2,3,4])
y = np.random.randn(5)
y = np.array([1,2,3,4,5])

# matrix addition
print("A + B = \n", A + B)

# matrix subtraction
print("A - B = \n", A - B)

# Elementwise multiplication
print(" A * B = \n", A*B)

# Elementwise division
print(" A / B = \n", A/B)

# Multiply columns by x
print(" A * x = \n", A*x)

# Multiply rows by y
print("y[:,None] = \n", y[:,None])
print(" A * y[:,None] = \n", A*y[:,None])

# Transpose of A
print("A.T = \n", A.T)

A + B = 
 [[ 0.09380148 -2.08996867  3.09785479  2.75649783]
 [ 5.05119327  4.44349111  6.82778163  7.90555174]
 [ 8.47852315  9.04866474  8.752957   11.80925258]
 [11.65110845 12.90184127 14.4429844  16.35189977]
 [14.29361433 18.03530224 17.8522298  20.55787796]]
A - B = 
 [[-0.09380148  4.08996867  0.90214521  3.24350217]
 [ 2.94880673  5.55650889  5.17221837  6.09444826]
 [ 7.52147685  8.95133526 11.247043   10.19074742]
 [12.34889155 13.09815873 13.5570156  13.64810023]
 [17.70638567 15.96469776 18.1477702  17.44212204]]
 A * B = 
 [[  0.          -3.08996867   2.19570959  -0.73050652]
 [  4.20477306  -2.78254443   4.96668979   6.33886219]
 [  3.82818518   0.4379827  -12.47042998   8.90177833]
 [ -4.18669855  -1.2760635    6.2017816   20.27849648]
 [-27.3021707   17.60013816  -2.65986359  29.59968129]]
 A / B = 
 [[   0.           -0.32362788    1.82173454  -12.3202185 ]
 [   3.80519941   -8.98458251    7.24828841    7.73009391]
 [  16.71810455  184.93881344   -8.01896969   13.592

## Matrix operations

In [88]:
A = np.random.randn(5,4)
A = np.arange(20).reshape(5,4)
C = np.random.randn(4,3)
x = np.random.rand(4)
x = np.array([1,2,3,4])
y = np.random.rand(5)
z = np.array([1,2,3,4])

print("A =\n", A)
print("A @ C = \n", A @ C)   # Matrix Matrix multiplication
print("A @ x = \n", A @ x)   # Matrix vector multiplication
print("x @ z = \n",x @ z)    # inner product or dot product resulting in scalar value

print("A.T @ y = \n", A.T @ y) # matrix vector multiply
print("y.T @ A = \n", y.T @ A) # same as above

print("y @ A =\n", y @ A)

A =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
A @ C = 
 [[  3.16837284  -5.06957917   6.50673556]
 [  6.56851025 -16.96288216  15.97930255]
 [  9.96864767 -28.85618515  25.45186954]
 [ 13.36878508 -40.74948814  34.92443652]
 [ 16.7689225  -52.64279114  44.39700351]]
A @ x = 
 [ 20  60 100 140 180]
x @ z = 
 30
A.T @ y = 
 [10.2747763 12.2114071 14.1480379 16.0846687]
y.T @ A = 
 [10.2747763 12.2114071 14.1480379 16.0846687]
y @ A =
 [10.2747763 12.2114071 14.1480379 16.0846687]


## Solving Linear Equation

In [92]:
b = np.array([-13, 9])
A = np.array([[4, -5],[-2, 3]])

print("inv(A) = ", np.linalg.inv(A))
print("inv(A) @ b = ", np.linalg.inv(A) @ b)
print("solving for x = ", np.linalg.solve(A,b))  # preferred method as it is computationally cheaper than above method
# solution method uses the LU factorization which is cheaper than computing inverses
# forgot about LU decomposition? Check out the link for a quick refresher on LU decomposition
# => https://www.youtube.com/watch?v=rhNKncraJMk

inv(A) =  [[1.5 2.5]
 [1.  2. ]]
inv(A) @ b =  [3. 5.]
solving for x =  [3. 5.]


## Complexity of operations
Assume A, B => (n*n) & x,y => n

### Matrix-matrix product AB: O(n^3)
### Matrix-vector product Ax: O(n^2)
### Vector-vector inner product X.T y: O(n)
### Matrix inverse/ solve: A^-1, A^-1 y: O(n^3)

### Important:  Be careful about the order of operations, (AB)x = A(Bx) but the left one is O(n^3), right one is O(n^2)

In [96]:
A = np.random.randn(10,10)
B = np.random.randn(10,10)
x = np.random.randn(10)

In [97]:
%%timeit 
A @ B @ x       # numpy default takes left to right resulting in (AB)x

2.21 µs ± 85 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [99]:
%%timeit 
A @ (B @ x)    # parenthesis matters!! Resulting in much faster computation

1.7 µs ± 25.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Sparse matrices
## Coordinate (coo) format

In [107]:
from scipy.sparse import coo_matrix

# constructing a matrix using i,j,v format
row_indices = np.array([1,3,2,0,3,1])
col_indices = np.array([0,0,1,2,2,3])
data = np.array([2,4,1,3,1,1])
x = coo_matrix((data,(row_indices, col_indices)), shape=(4,4)).toarray()

array([[0, 0, 3, 0],
       [2, 0, 0, 1],
       [0, 1, 0, 0],
       [4, 0, 1, 0]])

## Compressed sparse column (CSC) format

#### data = [2 4 1 3 1 1]
#### row_indices = [1 3 2 0 3 1]
#### col_ptr = [0 2 3 5 6]
#### col_ptr is not the same as col_indices. This is different. It keeps track of the starting positions of non-zero elements in each column. The last number 6 is the number of non-zero elements in this matrix

#### to create a matrix in CSC format, the coo_Matrix offers a tocsc method out of the box

In [114]:
x = coo_matrix((data,(row_indices, col_indices)), shape=(4,4))
x_csc = x.tocsc()
print(x_csc.toarray())

[[0 0 3 0]
 [2 0 0 1]
 [0 1 0 0]
 [4 0 1 0]]


In [119]:
# dense format
x_dense = x.todense()  ## this is in matrix format
np.asarray(x_dense)

array([[0, 0, 3, 0],
       [2, 0, 0, 1],
       [0, 1, 0, 0],
       [4, 0, 1, 0]])